version: '3'

volumes:
  omnihr_assignment_local_postgres_data: {}
  omnihr_assignment_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: omnihr_assignment_local_django
    container_name: omnihr_assignment_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: omnihr_assignment_production_postgres
    container_name: omnihr_assignment_local_postgres
    volumes:
      - omnihr_assignment_local_postgres_data:/var/lib/postgresql/data
      - omnihr_assignment_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: omnihr_assignment_local_docs
  #   container_name: omnihr_assignment_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./omnihr_assignment:/app/omnihr_assignment:z
  #   ports:
  #     - '9000:9000'
  #   command: /start-docs

  redis:
    image: redis:6
    container_name: omnihr_assignment_local_redis
    ports:
      - '6379:6379'
  # celeryworker:
  #   <<: *django
  #   image: omnihr_assignment_local_celeryworker
  #   container_name: omnihr_assignment_local_celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: omnihr_assignment_local_celerybeat
  #   container_name: omnihr_assignment_local_celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: omnihr_assignment_local_flower
  #   container_name: omnihr_assignment_local_flower
  #   ports:
  #     - '5555:5555'
  #   command: /start-flower
